name: 'forum'

services:
  frontend:
    build:
      context: ./frontend
    env_file:
      ./frontend/.env
    command: npm run docker-dev
    volumes:
      - ./frontend/src:/usr/src/app/src
  postgres:
    image: postgres:16
    env_file:
      - ./postgres_auth/.env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${APP__DATABASE__USER}'"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - "5432:5432"
  postgres-auth:
    image: postgres:16
    env_file:
      - ./postgres_auth/.env
    volumes:
      - ./postgres_auth/data:/var/lib/postgrsql/data
    ports:
      - "9451:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${APP__DATABASE__USER}'"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  backend-auth:
    build: ./backend/auth
    env_file: 
      - backend/auth/.env
    depends_on:
      - postgres-auth
      - auth-run-migrations
    volumes:
      - ./backend/auth/src:/usr/src/app/src
    ports:
      - "7652:8000"
  backend-basic:
    build: ./backend/basic
    env_file: 
      - backend/basic/.env
    depends_on:
      - postgres
      - basic-run-migrations
    volumes:
      - ./backend/basic/src:/usr/src/app/src
    ports:
      - "7653:8000"
  nginx:
    build: ./nginx
    volumes:
      - ./nginx:/nginx
    env_file:
      - nginx/.env
    ports:
      - "8000:80"
    depends_on:
      - backend-auth
      - frontend
  auth-tool-alembic:
    profiles:
      - tools
    build: ./backend/auth
    depends_on:
      - postgres-auth
    entrypoint: alembic
    env_file:
      - ./backend/auth/.env
    volumes:
      - ./backend/auth/alembic:/usr/src/app/alembic
  auth-run-migrations:
    build: ./backend/auth
    depends_on:
      - postgres-auth
    entrypoint: alembic upgrade head
    env_file:
      - ./backend/auth/.env
    volumes:
      - ./backend/auth/alembic:/usr/src/app/alembic
  basic-tool-alembic:
    profiles:
      - tools
    build: ./backend/basic
    depends_on:
      - postgres
    entrypoint: alembic
    env_file:
      - ./backend/basic/.env
    volumes:
      - ./backend/basic/alembic:/usr/src/app/alembic
  basic-run-migrations:
    build: ./backend/basic
    depends_on:
      - postgres
    entrypoint: alembic upgrade head
    env_file:
      - ./backend/basic/.env
    volumes:
      - ./backend/basic/alembic:/usr/src/app/alembic
