name: 'forum'

services:
  frontend:
    build:
      context: ./frontend
    env_file:
      ./frontend/.env
    command: npm run docker-dev
    volumes:
      - ./frontend/src:/usr/src/app/src
  postgres:
    image: postgres:16
    env_file:
      - ./postgres_auth/.env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  postgres-auth:
    image: postgres:16
    env_file:
      - ./postgres_auth/.env
    volumes:
      - ./postgres_auth/data:/var/lib/postgrsql/data
    ports:
      - "9451:5432"
  backend-auth:
    build: ./backend/auth
    env_file: 
      - backend/auth/.env
    depends_on:
      - postgres-auth
    volumes:
      - ./backend/auth/src:/usr/src/app/src
    ports:
      - "7652:8000"
  nginx:
    build: ./nginx
    volumes:
      - ./nginx:/nginx
    env_file:
      - nginx/.env
    ports:
      - "8000:80"
    depends_on:
      - backend-auth
      - frontend
  tool-alembic:
    profiles:
      - tools
    build: ./backend/auth
    depends_on:
      - postgres-auth
    entrypoint: alembic
    env_file:
      - ./backend/auth/.env
    volumes:
      - ./backend/auth/alembic:/usr/src/app/alembic
  auth-run-migrations:
    build: ./backend/auth
    depends_on:
      - postgres-auth
    entrypoint: alembic upgrade head
    env_file:
      - ./backend/auth/.env
    volumes:
      - ./backend/auth/alembic:/usr/src/app/alembic
