"""empty message

Revision ID: 8c4f660527d5
Revises: bf6eda1fbd92
Create Date: 2025-07-07 09:47:00.732549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c4f660527d5'
down_revision: Union[str, None] = 'bf6eda1fbd92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_role_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'user', 'user_roles', ['user_role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_role_id')
    # ### end Alembic commands ###
