"""Initial

Revision ID: bf6eda1fbd92
Revises: 
Create Date: 2025-06-23 18:00:56.161137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf6eda1fbd92'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nick', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nick')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('can_use_global_activity', sa.Boolean(), nullable=False),
    sa.Column('can_send_messages', sa.Boolean(), nullable=False),
    sa.Column('can_make_new_friends', sa.Boolean(), nullable=False),
    sa.Column('have_mod_access', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_session',
    sa.Column('session_token', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_dark_theme', sa.Boolean(), nullable=False),
    sa.Column('is_accepting_new_friends', sa.Boolean(), nullable=False),
    sa.Column('is_mail_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_using_mail_2fa', sa.Boolean(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('town', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_to_friend',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('friendId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['friendId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_to_friend')
    op.drop_table('user_settings')
    op.drop_table('user_session')
    op.drop_table('user_roles')
    op.drop_table('user')
    # ### end Alembic commands ###
